# Data Configuration
data:
  merra2_dir: "data/merra2"
  prism_dir: "data/prism"
  dem_dir: "data/dem"
  dem_file: "PRISM_us_dem_4km_bil.bil"
  dates: ["20250301", "20250302"]  # List of dates to use in training
  spatial_extent: null  # null for whole domain, or [min_lon, min_lat, max_lon, max_lat]
  cache_dir: "cache"
  patch_size: 64  # Size of spatial patches for training
  input_vars: ["T2MMAX", "T2MMEAN", "T2MMIN", "TPRECMAX"]
  target_vars: ["tdmean", "ppt"]  # PRISM variables (mean temperature and precipitation)
  mask_ratio: 0.3  # Ratio of pixels to mask for training
  train_test_split: [0.7, 0.15, 0.15]  # Train, val, test split

# Model Configuration
model:
  prithvi_checkpoint: "ibm/prithvi-100m-wxc"  # HuggingFace model ID
  use_pretrained: true
  freeze_encoder: false
  unfreeze_layers: []  # Layers to unfreeze if encoder is frozen
  embedding_dim: 768
  upsampling_scales: [2, 2]  # Upsampling scales at each level
  dropout: 0.1
  auxiliary_input: true  # Whether to use DEM as auxiliary input

# Training Configuration
training:
  epochs: 30
  batch_size: 8
  optimizer:
    name: "AdamW"
    lr: 1.0e-4
    weight_decay: 0.01
  scheduler:
    name: "cosine"
    warmup_epochs: 3
  precision: 16  # Use mixed precision training (16 or 32)
  gradient_clip_val: 1.0
  log_every_n_steps: 50
  val_check_interval: 1.0  # Fraction of epoch to run validation
  save_top_k: 3  # Number of best checkpoints to save

# Loss Configuration
loss:
  mae_weight: 1.0
  mse_weight: 0.5
  ssim_weight: 0.2  # Structural similarity index measure

# Logging and Checkpoints
logging:
  save_dir: "logs"
  name: "merra2-prism-downscaling"
  version: null  # Auto-increment
  log_graph: true
  tensorboard: true
  wandb: false
  wandb_project: "merra2-prism-downscaling"

# Hardware
hardware:
  accelerator: "auto"  # "cpu", "gpu", "tpu", or "auto"
  devices: 1
  num_workers: 4
  pin_memory: true 